# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    view:
        view_response_listener:  true
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
    exception:
        exception_controller: 'fos_rest.exception.controller:showAction'
        codes:
            Symfony\Component\HttpKernel\Exception\NotFoundHttpException: 404
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violationList
    param_fetcher_listener: true
